# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeApp' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeApp

  

  platform :ios, '9.0'
  target 'ReactNativeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeApp-tvOS

  target 'ReactNativeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
